In [1]:
import numpy as np

- Генерация массивов со случайными значениями

In [3]:
# 1-мерный массив (вектор-строки) случайных целых значений
arr_0 = np.random.randint(3, size=10)
arr_0

array([1, 1, 2, 1, 0, 0, 2, 0, 2, 1])

In [4]:
np.random.randint(-10, 10, size=10)


array([-5, -1, -6,  3,  1, -8,  2, -4, -9,  8])

In [6]:
# 2-мерный массив (вектор-столбец) случайных целых значений
arr_1 = np.random.randint(100, size=(7, 2))
arr_1

array([[51, 34],
       [18, 73],
       [34, 84],
       [39, 92],
       [ 9, 34],
       [ 1, 88],
       [91, 10]])

In [7]:
# случайное скалярное значение
np.random.randint(10, 50)

17

In [9]:
# 2-мерный массив (матрица) случайных целых значений
arr_2 = np.random.randint(100, size=(3, 5, 4))
arr_2

array([[[94, 18, 92,  2],
        [83, 94, 99, 43],
        [91, 70, 84, 24],
        [94, 88, 90, 37],
        [43, 61, 82, 27]],

       [[69, 50, 71, 10],
        [ 4, 98, 54, 88],
        [45,  1,  6, 66],
        [24, 67, 76, 11],
        [16,  6, 12, 72]],

       [[73, 67, 50, 84],
        [52, 92, 65, 23],
        [37, 51, 34, 22],
        [54, 24, 19, 28],
        [82, 14, 74, 60]]])

In [10]:
# 2-мерный массив (матрица) случайных чисел с плавающей точкой в диапазоне от 0 до 1

np.random.rand(3)

array([0.00411351, 0.55408166, 0.15461582])

In [13]:
# 2-мерный массив (матрица) случайных чисел с плавающей точкой в диапазоне от 0 до 1

np.random.rand(3, 3, 3)

array([[[0.45003593, 0.08374659, 0.18435381],
        [0.21084557, 0.81837776, 0.06993229],
        [0.29339332, 0.05710569, 0.20380635]],

       [[0.657173  , 0.24968376, 0.18982297],
        [0.94764614, 0.70490121, 0.82359023],
        [0.61782511, 0.00349137, 0.61971342]],

       [[0.13304418, 0.02622377, 0.67554599],
        [0.55733387, 0.11192451, 0.43585999],
        [0.7106343 , 0.33418121, 0.45583427]]])

In [14]:
np.random.random((3, 2))

array([[0.55464156, 0.55844443],
       [0.09921224, 0.15363163],
       [0.07359952, 0.57176336]])

In [15]:
# массив (матрица) случайных чисел с плавающей точкой 
# из нормального (гауссова) распределения

np.random.randn(3, 3)

array([[-1.24973443,  0.14449547, -1.68388349],
       [-1.65569581,  0.36286873,  1.70818702],
       [-1.20644995,  0.91115092, -0.98678333]])

In [ ]:
- Атрибуты

In [16]:
# по форме массива
arr_0.shape

(10,)

In [17]:
arr_1.shape

(7, 2)

In [19]:
# тип данных
arr_0.dtype

dtype('int32')

In [21]:
arr_1.dtype

dtype('int32')

In [22]:
# мерность массива (количество измерений/осей массива)
arr_0.ndim

1

In [23]:
arr_1.ndim

2

In [24]:
arr_2.ndim

3

In [26]:
# объем памяти (в байтах), занимаемый массивом
arr_2.nbytes

240

In [27]:
# количество всех элементов массива
arr_2.size

60

In [ ]:
- Методы

In [28]:
# конвертация типов данных
arr_2.dtype

dtype('int32')

In [29]:
arr_2.astype("float16")

array([[[94., 18., 92.,  2.],
        [83., 94., 99., 43.],
        [91., 70., 84., 24.],
        [94., 88., 90., 37.],
        [43., 61., 82., 27.]],

       [[69., 50., 71., 10.],
        [ 4., 98., 54., 88.],
        [45.,  1.,  6., 66.],
        [24., 67., 76., 11.],
        [16.,  6., 12., 72.]],

       [[73., 67., 50., 84.],
        [52., 92., 65., 23.],
        [37., 51., 34., 22.],
        [54., 24., 19., 28.],
        [82., 14., 74., 60.]]], dtype=float16)

In [31]:
# транспонирование - поворот массива по диагонали
arr_2.transpose()

array([[[94, 69, 73],
        [83,  4, 52],
        [91, 45, 37],
        [94, 24, 54],
        [43, 16, 82]],

       [[18, 50, 67],
        [94, 98, 92],
        [70,  1, 51],
        [88, 67, 24],
        [61,  6, 14]],

       [[92, 71, 50],
        [99, 54, 65],
        [84,  6, 34],
        [90, 76, 19],
        [82, 12, 74]],

       [[ 2, 10, 84],
        [43, 88, 23],
        [24, 66, 22],
        [37, 11, 28],
        [27, 72, 60]]])

In [32]:
# транспонирование - поворот массива по диагонали
arr_2.T

array([[[94, 69, 73],
        [83,  4, 52],
        [91, 45, 37],
        [94, 24, 54],
        [43, 16, 82]],

       [[18, 50, 67],
        [94, 98, 92],
        [70,  1, 51],
        [88, 67, 24],
        [61,  6, 14]],

       [[92, 71, 50],
        [99, 54, 65],
        [84,  6, 34],
        [90, 76, 19],
        [82, 12, 74]],

       [[ 2, 10, 84],
        [43, 88, 23],
        [24, 66, 22],
        [37, 11, 28],
        [27, 72, 60]]])

In [36]:
arr_3 = np.random.rand(3, 4)
arr_3

array([[0.53793289, 0.9473215 , 0.07017635, 0.937771  ],
       [0.65211436, 0.90752021, 0.78474863, 0.48160416],
       [0.98326828, 0.68492921, 0.61064485, 0.81174023]])

In [37]:
# минимальное значение
arr_3.min()

0.07017634620099933

In [38]:
# максимальное значение
arr_3.max()

0.9832682758790948

In [39]:
# минимальное значение по определенной оси
arr_3.min(axis=0)

array([0.53793289, 0.68492921, 0.07017635, 0.48160416])

In [44]:
# среднее значение
arr_3.mean()

0.7008143049829932

In [45]:
arr_0

array([1, 1, 2, 1, 0, 0, 2, 0, 2, 1])

In [46]:
# индекс минимального значения
arr_0.argmin()

4

In [47]:
# индекс максимального значения
arr_0.argmax()

2

In [49]:
arr_4 = np.random.randint(10, size=10)
arr_4

array([1, 4, 5, 6, 8, 0, 4, 8, 3, 4])

In [52]:
# сортировка массива
arr_4.sort()
arr_4

array([0, 1, 3, 4, 4, 4, 5, 6, 8, 8])

In [53]:
# переворот

arr_4[::-1]

array([8, 8, 6, 5, 4, 4, 4, 3, 1, 0])

In [ ]:
- Индексация

In [54]:
arr_5 = np.random.randint(10, size=(3, 4))
arr_5

array([[6, 3, 0, 9],
       [4, 2, 8, 1],
       [4, 2, 7, 9]])

In [55]:
# прямая индексация
arr_5[1]

array([4, 2, 8, 1])

In [56]:
# обратная индексация
arr_5[-1]

array([4, 2, 7, 9])

In [57]:
# извлечение значений элементов массива
# синтаксис списков и кортежей
arr_5[2][2]

7

In [59]:
# синтаксис NumPy
arr_5[1, 2]

8

In [60]:
# запись значений
arr_5[2, 2] = 1000
arr_5

array([[   6,    3,    0,    9],
       [   4,    2,    8,    1],
       [   4,    2, 1000,    9]])

- Срезы

In [61]:
arr_5

array([[   6,    3,    0,    9],
       [   4,    2,    8,    1],
       [   4,    2, 1000,    9]])

In [62]:
# срез строк
arr_5[1:]

array([[   4,    2,    8,    1],
       [   4,    2, 1000,    9]])

In [63]:
# срез столбцов
arr_5[:, 1:]

array([[   3,    0,    9],
       [   2,    8,    1],
       [   2, 1000,    9]])

In [64]:
# срез строк и столбцов
arr_5[:2, 1:]

array([[3, 0, 9],
       [2, 8, 1]])

In [65]:
arr_6 = arr_5[:2, 1:]
arr_6

array([[3, 0, 9],
       [2, 8, 1]])

In [66]:
# срез массива не создает независимый массив
# а создает представление исходного массива
arr_6[0,0] = 10
arr_6

array([[10,  0,  9],
       [ 2,  8,  1]])

In [67]:
arr_5

array([[   6,   10,    0,    9],
       [   4,    2,    8,    1],
       [   4,    2, 1000,    9]])

In [68]:
# копия массива
arr_7 = arr_5[:2, 1:].copy()
arr_7

array([[10,  0,  9],
       [ 2,  8,  1]])

In [70]:
arr_7[0,0] = 1000
arr_7

array([[1000,    0,    9],
       [   2,    8,    1]])

In [71]:
arr_5

array([[   6,   10,    0,    9],
       [   4,    2,    8,    1],
       [   4,    2, 1000,    9]])

In [72]:
# "зерно" ГПСЧ (генератора случайных чисел)

np.random.seed(0)

np.random.randint(10, size=5)

array([5, 0, 3, 3, 7])